
Running tests... 
----------------------------------------------------------------------
 case (AutoInput.CasePackage.En_ClickSugg_Input.CaseOne) ... ERROR (20.321311)s

======================================================================
ERROR [20.321311s]: AutoInput.CasePackage.En_ClickSugg_Input.CaseOne.case
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xm20190901/PycharmProjects/uiautomator2Test/AutoInput/CasePackage/En_ClickSugg_Input.py", line 22, in case
    d.xpath(
  File "/Users/xm20190901/PycharmProjects/uiautomator2Test/venv/lib/python3.8/site-packages/uiautomator2/xpath.py", line 589, in click
    el = self.get(timeout=timeout)
  File "/Users/xm20190901/PycharmProjects/uiautomator2Test/venv/lib/python3.8/site-packages/uiautomator2/xpath.py", line 518, in get
    raise XPathElementNotFoundError(self._xpath_list)
uiautomator2.exceptions.XPathElementNotFoundError: ['//*[@resource-id="android:id/content"]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[4]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/androidx.recyclerview.widget.RecyclerView[1]/android.view.ViewGroup[4]']

----------------------------------------------------------------------
Ran 1 test in 0:00:20

FAILED
 (Errors=1)

Generating HTML reports... 
../../../AutoInput/Reports/TestResults_AutoInput.CasePackage.En_ClickSugg_Input.CaseOne_2021-01-26_17-44-54.html
